kind: ConfigMap
apiVersion: v1
metadata:
  name: eap-config
data: 
  DATASOURCES: "POSTGRESQL"
  POSTGRESQL_DATABASE: "postgresDB"
  POSTGRESQL_NAME: "CoolstoreDS"
  POSTGRESQL_DRIVER: "postgresql"
  POSTGRESQL_DATASOURCE: "CoolstoreDS"
  POSTGRESQL_USER: "postgresDB"
  POSTGRESQL_USERNAME: "postgresDB"
  POSTGRESQL_PASSWORD: "postgresPW"
  POSTGRESQL_URL: "jdbc:postgresql://postgresql:5432/"
  POSTGRESQL_JNDI: "java:jboss/datasources/CoolstoreDS"
  POSTGRESQL_NONXA: "true"
  MQ_SERVICE_PREFIX_MAPPING: "eap74-amq7=MQ"
  EAP74_AMQ_TCP_SERVICE_HOST: "eap74-amq7-hdls-svc.amq3.svc.cluster.local"
  EAP74_AMQ_TCP_SERVICE_PORT: "61616"
  MQ_USERNAME: "Mf7L1Sj9"
  MQ_PASSWORD: "Q8twbO9U"
  MQ_QUEUES: "orders"
  AMQ_JNDI: "java:/ConnectionFactory"
