apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: rhsso-operator
  namespace: eap
spec:
  targetNamespaces:
  - eap

---

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: sso-operator
  namespace: eap
spec:
  channel: stable
  name: rhsso-operator
  source: redhat-operators 
  sourceNamespace: openshift-marketplace 
