apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  name: example-realm-user
  labels:
    app: sso
  namespace: eap
spec:
  realmSelector:
    matchLabels:
      app: sso
  user:
    credentials:
      - type: password
        value: pass
    username: user1
    firstName: John
    lastName: Doe
    email: user@example.com
    enabled: true
    emailVerified: false